// <auto-generated />
using DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataModels.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataModels.FlowerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BloomTime");

                    b.Property<string>("Description");

                    b.Property<string>("Humidity");

                    b.Property<string>("LatinName");

                    b.Property<string>("Light");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<string>("TitleImage");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloomTime = "summer",
                            Description = "A plant that lasts many years and is characterised by its big and beautiful flowers that can be in many vivid colours.",
                            Humidity = "low",
                            LatinName = "Gerbera Daisy",
                            Light = "sunlight",
                            Name = "Daisy",
                            Price = 120,
                            TitleImage = "https://github.com/kristina-s/Frontend-project-resourses/blob/master/images/branch/title-imgs/daisy-title.jpg?raw=true",
                            Type = "Branch"
                        });
                });

            modelBuilder.Entity("DataModels.OrderDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("CreditCardNumber");

                    b.Property<string>("FullName");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
